version: 1
accounts:
  - name: alice
    coins: ["2000000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
    address: "cosmos1k5u3yecxsx0z999mfutxserd6ssvyhp8gj3rd7"
validators:
  - name: alice
    bonded: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: alice
  coins: ["5token", "100000stake"]
  coins_max: ["100token", "100000stake"]
  rate_limit_window: "60s"
